# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LQUmengNew' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LQUmengNew
  #基本
  pod 'UMCCommon', '~>1.5.0'
  pod 'UMCSecurityPlugins', '~>1.0.6'
  pod 'UMCCommonLog', '~>1.0.0'
  pod 'UMCErrorCatch', '~>1.0.0'
  
  #统计
  #pod 'UMCAnalytics'
  
  #推送
  pod 'UMCPush', '~>3.2.0'
  
  #分享
  # U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMCShare/UI', '~>6.9.0'
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat', '~>6.9.0'
  
  # 集成微信(完整版14.4M)
  #pod 'UMCShare/Social/WeChat'
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ', '~>6.9.0'
  # 集成QQ/QZone/TIM(完整版7.6M)
  #pod 'UMCShare/Social/QQ'
  # 集成新浪微博(精简版1M)
  pod 'UMCShare/Social/ReducedSina', '~>6.9.0'
  # 集成新浪微博(完整版25.3M)
  #pod 'UMCShare/Social/Sina'
  
  
  target 'LQUmengNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LQUmengNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
